name: check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 8 * * *"

jobs:
  test:
    name: test ${{ matrix.py }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - Ubuntu
        py:
          - "3.13"
    steps:
      - name: Setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}
      - uses: actions/checkout@v4
      - name: Install tox-gh
        run: python -m pip install tox-gh
      - name: Install script requirements
        run: python -m pip install -r scripts/requirements.txt
      - name: Setup test suite
        run: tox r -vv --notest
      - name: Run test suite
        run: tox -e test,validate
        env:
          PYTEST_ADDOPTS: "-vv --durations=10"
